title: 'Quantified Ketonian'
description: 'Quantifying my journey through ketosis'
author:
  name: 'Justin Mitchell'
paginate: 5
sidebar_home_link: true
google_analytics: 'UA-135909020-1'
momently_url: '//s3-us-west-2.amazonaws.com/momently-static/loader/mA8HAwAqAQ0_momently.js'